[project]
name = "autodesk"
version = "1.0.0"
description = "Automatic standing desk controller."
readme = "README.md"
authors = [
    { name = "Daniel Oom", email = "oom.daniel@gmail.com" },
]
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "aiohttp-jinja2==1.6",
    "aiohttp==3.9.5",
    "matplotlib==3.9.0",
    "numpy==1.26.4",
    "pandas==2.2.2",
    "pyftdi==0.55.4",
    "pyyaml==6.0.1",
]
requires-python = ">=3.12"

[project.urls]
homepage = "https://github.com/daoo/autodesk"

[tool.uv]
dev-dependencies = [
    "mock==5.1.0",
    "pyright>=1.1.382.post1",
    "pytest-aiohttp==1.0.5",
    "pytest-asyncio==0.23.7",
    "pytest-cov==5.0.0",
    "pytest-mock==3.14.0",
    "pytest==8.2.1",
    "requests==2.32.3",
    "ruff>=0.6.8",
]
