name: autodesk continuous integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: ci.sh script
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-ci.txt
    - name: Lint with flake8
      run: ci.sh
    - name: Upload codecov
      uses: codecov/codecov-action@v1.0.15
